### PR TITLE
[WNMGDS-457] Change HelpDrawerToggle to use inline instead of inline-block

### LINKED ISSUE #689: HelpDrawerToggle uses inline-block rather than inline when inline prop set to true
**Describe the bug**

The `HelpDrawerToggle` DS component has a prop named ‘inline’ that is supposed to set the container span to “display inline or block”, but it adds `display: inline-block`; when `<HelpDrawerToggle inline=true>`. This can cause display issues when the `HelpDrawerToggle` is a string of text in a paragraph element, particularly on small/mobile screen sizes.

**To Reproduce**

Create a `<HelpDrawerToggle inline=true>` with a sentence with of text as the link and place it in a paragraph with other text. See first screenshot.

We are able to override the default style to force `display: inline !important;`, but it seems like `< HelpDrawerToggle inline=true>` should use inline rather than inline-block.

**Expected behavior**

We expect that `<HelpDrawerToggle inline=true>` would apply the `display: inline;` style to the element, not `display: inline-block;`.

**Screenshots**

Using Chrome DevTools at mobile screen sizes

**What we get:**
localhelp test healthcare gov_(iPhone 5_SE)

**What we expected:**
localhelp test healthcare gov_(iPhone 5_SE) (1)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 81
Using the responsive design tools in Chrome DevTools to size to screen widths <768px 

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS:  N/A
 - Browser  N/A
 - Version  N/A

**Additional context**

### PR DESCRIPTION
**Pull request by nichia**
### Changed
- Change to use inline style when `inline` prop is set for `<HelpDrawerToggle>` component

### How to test
- Update HelpDrawer.example.jsx to replace this section `<HelpDrawerToggle ... </HelpDrawerToggle>` with below code
`        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
          ut labore et dolore magna aliqua. <span> </span>
          <HelpDrawerToggle
            inline
            helpDrawerOpen={this.state.showHelp}
            showDrawer={() => this.handleDrawerOpen()}
          >
          Toggle the help drawer Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua
          </HelpDrawerToggle>
          .
        </p>`
- Run the design system site locally and check that the drawer text link stays on the same line as the paragraph.

### Fixed
- Fixes #689

### CODE REVIEW

**Comment by nichia** [comment]
Hey @dcloud, I've updated the code to apply `display: inline;` instead of `display: inline-block;` however, I'm not able to replicate the issue, so i cannot really test that the change has fixed the line break. 

The example you included in the issue #689 is clear and helpful. Can you also show the html code for this example?

**Comment by dcloud** [comment]
From the [FLH Results page](https://localhelp.healthcare.gov/#/results?lat=36.028416&lng=-78.92828159999999&state=NC) (which currently has a style override to get `inline !important`):

```
<div class="ds-u-margin-bottom--2 flh-c-help-drawer-toggle"><strong>Agents/brokers and assisters </strong>are trained and certified by the Marketplace to provide application help. <span class="ds-u-display--inline-block"><a href="javascript:void(0);" class="qa-help-drawer-toggle">Learn about the differences between agents/brokers and assisters</a></span>.</div>
```

**Comment by nichia** [comment]
Thanks @dcloud - after changing to `display: inline`, the helpdrawer text link now stays on the same line as the paragraph. However, it has removed the space separator ([see attached](https://drive.google.com/drive/u/0/folders/0AAq79C_GQhE4Uk9PVA)). Did you come across the same issue and had to find another way to add a space before the helpdrawer text link?

**Comment by whatbird** [comment]
@nichia unless i'm misunderstanding, the missing space is just due to good ol' HTML whitespace rendering.

it may not be the responsibility of the HelpDrawer to apply the surrounding whitespace, and a preceding `{" "}` or additional CSS should solve the spacing issue.

**Comment by nichia** [comment]
Thanks @dcloud @whatbird, looks like I'm good to go with it now.

File: packages/design-system/src/components/HelpDrawer/HelpDrawerToggle.jsx [hunk 1]
```diff
@@ -12,7 +12,7 @@ export class HelpDrawerToggle extends React.PureComponent {
   }
 
   render() {
-    const blockInlineClass = `ds-u-display--${this.props.inline ? 'inline-block' : 'block'}`;
```
Comment (bernardwang) [inline packages/design-system/src/components/HelpDrawer/HelpDrawerToggle.jsx:15]: We should rename this class to be `inlineClass` as well

File: packages/design-system/src/styles/utilities/_display-visibility.scss [hunk 2]
```diff
@@ -9,6 +9,10 @@
   display: inline-block !important;
 }
 
+.ds-u-display--inline {
```
Comment (bernardwang) [inline packages/design-system/src/styles/utilities/_display-visibility.scss:12]: Usually we don't want to add an additional utility for this type of ticket, however in this case it seems to make sense. Because we are adding, we should also update the documentation and examples for the display/visibility utility page

Comment (nichia) [reply packages/design-system/src/styles/utilities/_display-visibility.scss:12]: Good pick up. Done.

File: packages/design-system/src/components/HelpDrawer/HelpDrawerToggle.jsx [hunk 3]
```diff
@@ -12,11 +12,11 @@ export class HelpDrawerToggle extends React.PureComponent {
...
+    const inlineClass = `ds-u-display--${this.props.inline ? 'inline' : 'block'}`;
     /* eslint-disable jsx-a11y/anchor-is-valid */
     return (
       // Use a <span> since a <div> may be invalid depending where this link is nested
-      <span className={blockInlineClass}>
+      <span className={inlineClass}>
         <a
           href="javascript:void(0);"
           className={this.props.className}
```
Comment (line47) [inline packages/design-system/src/components/HelpDrawer/HelpDrawerToggle.jsx:22]: I'm thinking it would be good to update the `inline` prop description to be something like: `Applies an inline class to the toggle` 

The current description is a bit confusing

File: packages/design-system-docs/src/pages/utilities/display-visibility/_display-visibility.docs.scss [hunk 4]
```diff
@@ -11,9 +11,9 @@ Display
 
 > The display CSS property specifies the type of rendering box used for an element. In HTML, default display property values are taken from behaviors described in the HTML specifications or from the browser/user default stylesheet. &mdash; [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/display)
 
-**Format**: `.ds-u-display--[block|inline-block|flex|none]`
+**Format**: `.ds-u-display--[inline|block|inline-block|flex|none]`
 
-**Responsive format**: `.ds-u-[breakpoint]-display--[block|inline-block|flex|none]`
```
Comment (bernardwang) [inline packages/design-system-docs/src/pages/utilities/display-visibility/_display-visibility.docs.scss:16]: Could you move the inline after block? So the ordering is `block`, `inline`, `inline-block` etc

File: packages/design-system/src/components/HelpDrawer/HelpDrawerToggle.jsx (hunk 3 above)
Comment (nichia) [reply packages/design-system/src/components/HelpDrawer/HelpDrawerToggle.jsx:22]: Done

File: packages/design-system-docs/src/pages/utilities/display-visibility/_display-visibility.docs.scss (hunk 4 above)
Comment (bernardwang) [reply packages/design-system-docs/src/pages/utilities/display-visibility/_display-visibility.docs.scss:16]: I think `inline` should follow `block` so you can actually see the inline elements behaving together. I think its ok if it looks wonkier when you resize the screen, as thats expected with the inline element. 
Screen Shot 2020-06-04 at 2 16 52 PM

Comment (bernardwang) [reply packages/design-system-docs/src/pages/utilities/display-visibility/_display-visibility.docs.scss:16]: `block` also needs to go first in my opinon. If you look at [USWDS](https://designsystem.digital.gov/utilities/display/) they order it with block first. In fact, I think we should would move flex to second as well.

File: packages/design-system/src/components/HelpDrawer/HelpDrawerToggle.jsx [hunk 5]
```diff
@@ -37,7 +37,7 @@ HelpDrawerToggle.propTypes = {
   children: PropTypes.node.isRequired,
   /** Additional classes for the toggle button anchor element */
   className: PropTypes.string,
-  /** Add display inline or block to parent span */
+  /** Adds display inline or block style to the HelpDrawerToggle */
```
Comment (bernardwang) [inline packages/design-system/src/components/HelpDrawer/HelpDrawerToggle.jsx:40]: Personally I prefer:
> Adds `display: inline` to the `HelpDrawerToggle`

It doesnt actually add `block` style as thats the default.

File: packages/design-system-docs/src/pages/utilities/display-visibility/_display-visibility.docs.scss (hunk 4 above)
Comment (nichia) [reply packages/design-system-docs/src/pages/utilities/display-visibility/_display-visibility.docs.scss:16]: Okay, let's take a look at the change to this order - block|flex|inline|inline-block.
